version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    networks:
      - mynet
    environment:
      POSTGRES_USER: betuser
      POSTGRES_PASSWORD: betpassword
      POSTGRES_DB: betdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U betuser -d betdb']
      interval: 10s
      timeout: 5s
      retries: 10

  bet-system-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: bet-system-api
    networks:
      - mynet
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: betuser
      DB_PASS: betpassword
      DB_NAME: betdb
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  bet-system-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: bet-system-web
    networks:
      - mynet
    ports:
      - "5173:5173"
    depends_on:
      - bet-system-api

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge
